package pl.hellopoland.dto;

public enum RoleDTO {
  ROOT, ADMIN, HELPDESK_PARTNER_MANAGER, HELPDESK_CONTENT_MANAGER, HELPDESK_SUPPORT,
  HELPDESK_TECHNICAL, PARTNER, PARTNER_ADMIN, PARTNER_SALESMAN, SALESMAN, USHER, USER;
}
